config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'hello' => 'application#hello'
  resources 'todos' do
    delete 'destroy_many', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  scope :active, -> {where(completed: false)}
  scope :completed, -> {where(completed: true)}

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:update, :destroy]

  def index
    @todos = Todo.all
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      render @todo, status: :created
    else
      render inline: errors, status: :unprocessable_entity
    end

  end

  def update
    @todo.assign_attributes(todo_params)
    if @todo.save
      render @todo
    else
      render inline: errors, status: :unprocessable_entity
    end
  end

  def destroy
    @todo.destroy
  end

  def destroy_many
    Todo.where(id: params[:ids]).destroy_all
    head :no_content
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end


  def todo_params
    params.require(:todo).permit!
  end

  def errors
    @todo.errors.full_messages.join(', ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/hello.html.erb
<div data-controller="hello">
  <h1 data-target="hello.output">Say something...</h1>
  <button data-action="hello#greet">Greet!</button>
  <button data-action="hello#bye">Bye!</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LandOnStims</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo.html.erb
<li data-controller="todos-item"
    data-target="todos.todoItem"
    data-todos-item-locked="true"
    data-action="dblclick->todos-item#unlock">
  <%= form_with model: todo, data: {target: "todos-item.updateForm", type: 'html'} do |f| %>
    <%= f.hidden_field :id, data: {target: 'todos-item.id'} %>
    <%= label_tag nil do %>
      <%= f.check_box :completed, data: {action: "todos-item#check", target: "todos-item.completed"} %>
    <% end %>
    <%= f.text_field :name, data: {action: "blur->todos-item#lock", target: "todos-item.name"}, readonly: true %>
  <% end %>
  <%= link_to 'Destroy', todo, style: 'display: none;', data: {target: 'todos-item.destroy'}, method: :delete, remote: true %>
</li>

app/views/todos/index.html.erb
<div id="todos" data-controller="todos" data-todos-destroy-many-url="<%= destroy_many_todos_path %>">
  <%= form_with model: Todo.new, data: {target: "todos.addTodoForm", type: 'html'} do |f| %>
    <%= f.text_field :name, placeholder: "What u gonna do?", data: {target: "todos.newTodoName"} %>
    <span data-target="todos.errors"></span>
  <% end %>
  <ul data-target="todos.list">
    <%= render @todos %>
  </ul>
  <div>
    <div>Completed <span data-target="todos.completed"><%= Todo.completed.size %></span>/<span data-target="todos.all"><%= Todo.all.size %></span></div>
    <span>Show</span>
    <% ['All', 'Active', 'Completed'].each do |filter_name| %>
      <label>
        <input type="radio" name="filter" data-target="todos.filter" value="<%= filter_name.downcase %>"
               data-action="todos#applyFilter" <%= 'checked' if filter_name == 'All' %> /><%= filter_name %>
      </label>
    <% end %>
    <button data-action="todos#removeCompleted">Remove completed</button>
  </div>
</div>